### ISSUE TITLE
proj_2019_q4 file is blank

### ISSUE THREAD

**Issue by jmarquis024** [timp/jira-csv-roadmap#1]
Program runs but when I open the file, it is blank.

**Comment by timp** [comment]
Did you follow all the steps in the README?

**Comment by jmarquis024** [comment]
Yes

**Comment by jmarquis024** [comment]
I got it to run and give an output, but only 1 line is listed.  See screenshot.
![Screenshot](https://user-images.githubusercontent.com/73797657/98255141-16c5c480-1f4b-11eb-90f3-7c44fb46cfcb.png)

**Comment by timp** [comment]
What did you change to get it to run? 
How many lines were you expecting? 
What is it about the line Enable Security which is different to the others? 
There is little point in asking for my help if you will not do the basics!
Read the code and try to get the program to do what you expect.

**Comment by timp** [comment]
Ah 'joined 4 days ago'. 
You have much to learn. 
This is very famous: http://www.catb.org/~esr/faqs/smart-questions.html
Also filling in your profile picture and bio help people take you seriously, and trust you.

**Comment by jmarquis024** [comment]
I didn't have the dateutil installed so I installed that from pip. I made
no other changes and am using your original code and test data from Proj.

**Comment by jmarquis024** [comment]
I got this to work by changing the dates of the sample data.  Since everything was in the past they were not being displayed. 
![Screenshot 2](https://user-images.githubusercontent.com/73797657/98552995-21df6400-226d-11eb-80f4-13e147bbda66.jpg)

**Comment by timp** [comment]
Thank you for working through this. 
Do you want to make a PR for the README?

**Comment by jmarquis024** [comment]
Thank you for your patience, I haven't coded in python in a few years.

What is a PR?  One suggestion I would make is to say the developer needs
dateutil installed and they should change the year of the title to match
the current year. Other than that everything was clear.

**Comment by timp** [comment]
PR == Pull Request. 

Github makes it really easy, there is a Pencil icon in the top right of the reading pane of the README at the top level of the project. 

Edit on line and when you save a PR is created.
